# denopsのインストール
# curl -fsSL https://deno.land/x/install/install.sh | sh
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = '''
  call ddc#custom#patch_global('sources', ['nvim-lsp', 'file', 'skkeleton'])
  call ddc#custom#patch_global('completionMenu', 'pum.vim')
  call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['vim-denops/denops.vim']
on_event='InsertEnter'
hook_source = '''
lua << EOF
-- Skkeleton の最小限のキーバインド設定

-- Insert / Command モードで <C-j> を押すと SKK 有効化
vim.api.nvim_set_keymap('i', '<C-j>', '<Plug>(skkeleton-enable)', { noremap = true })
vim.api.nvim_set_keymap('c', '<C-j>', '<Plug>(skkeleton-enable)', { noremap = true })

-- Insert / Command モードで <C-l> を押すと SKK 無効化
vim.api.nvim_set_keymap('i', '<C-l>', '<Plug>(skkeleton-disable)', { noremap = true })
vim.api.nvim_set_keymap('c', '<C-l>', '<Plug>(skkeleton-disable)', { noremap = true })

-- skkeleton 設定 (辞書ファイル等)
-- curl -o ~/.skk/SKK-JISYO.L.gz http://openlab.jp/skk/dic/SKK-JISYO.L.gz && gunzip ~/.skk/SKK-JISYO.L.gz
vim.fn['skkeleton#config']({
  globalDictionaries = {
    "~/.skk/SKK-JISYO.L",
  },
  eggLikeNewline = true,
  keepState = true,
  showCandidatesCount = 2,
  registerConvertResult = true,
})

-- inputモード時に '/' キーを abbreviation 用に上書き
vim.fn['skkeleton#register_keymap']('input', '/', 'abbrev')
EOF
'''
